version: '3'

tasks:
  default:
    desc: "The default task" 
    cmds:
      - docker compose up -d
      - goreman start
      # - go-task run-localdns
      # - go-task run-landns

  run-landns:
    desc: "run landns"
    cmds:
      - docker compose exec --workdir /workspace/scripts/dev landns-dev go run main.go --bin landns

  run-landns-agent:
    desc: "run landns agent"
    cmds:
      - docker compose exec --workdir /workspace/scripts/dev landns-dev go run main.go --bin landns-agent

  proto:
    desc: "Generate protobuf"
    cmds:
      - docker compose exec landns-dev protoc --go_out=. --go_opt=paths=source_relative --twirp_out=. ./pkg/rpcgen/landns.proto

  rebuild-dev-image:
    desc: "Rebuild the development image"
    cmds:
      - docker compose up -d --build
  
  query:
    desc: "Query the DHCP Manager"
    cmds:
      - ssh root@192.168.100.101 "dig @127.0.0.1 archlinux.lan A"
  
  ssh:
    desc: "SSH to the server"
    cmds:
      - ssh root@192.168.100.101