version: '3'

tasks:
  default:
    desc: "The default task" 
    cmds:
      - go-task run-localdns
      # - go-task run-landns

  run-landns:
    desc: "Run the DHCP Manager"
    cmds:
      - docker compose exec landns-dev ssh root@192.168.100.101 pkill landns || true
      - docker compose up -d
      - docker compose exec --env CGO_ENABLED=0 landns-dev go build -o landns ./cmd/landns/main.go
      - docker compose exec landns-dev ssh root@192.168.100.101 rm -f /tmp/landns || true
      - docker compose exec landns-dev scp landns root@192.168.100.101:/tmp
      - docker compose exec landns-dev ssh root@192.168.100.101 /tmp/landns

  run-localdns:
    desc: "Run the localdns"
    cmds:
      - docker compose exec landns-dev ssh root@192.168.100.101 pkill localdns || true
      - docker compose up -d
      - docker compose exec --env CGO_ENABLED=0 landns-dev go build -o localdns ./cmd/landns/main.go
      - docker compose exec landns-dev ssh root@192.168.100.101 rm -f /tmp/localdns || true
      - docker compose exec landns-dev scp localdns root@192.168.100.101:/tmp
      - docker compose exec landns-dev ssh root@192.168.100.101 /tmp/localdns

  proto:
    desc: "Generate protobuf"
    cmds:
      - docker compose exec landns-dev protoc --go_out=. --go_opt=paths=source_relative --twirp_out=. ./pkg/rpcgen/landns.proto

  rebuild-dev-image:
    desc: "Rebuild the development image"
    cmds:
      - docker compose up -d --build
  
  query:
    desc: "Query the DHCP Manager"
    cmds:
      - ssh root@192.168.100.101 "dig @127.0.0.1 baidu.com A"
  
  ssh:
    desc: "SSH to the server"
    cmds:
      - ssh root@192.168.100.101